access_key: YAB77R70QJTVX4G5S1QY
secret_key: V3X0revhjlGvEE60baC5JsPO1xHWOLQGhDqD4g8L
host: de-dev-hh-1.s3.xws.x-ion.de
timeout: 20000
retries: 5
bucket_count: 10
bucket_name: HOSTNAME_%04d
bucket_offset: 0
max_ops_per_second: 100
object_count: 100
object_offset: 0
object_read_count: 1000
object_size: 256
thread_count: 2
