access_key: access
secret_key: secret
host: s3-endpoint.example.com
timeout: 20000
retries: 5
bucket_count: 100
HOSTNAME
bucket_offset: 0
object_count: 1000
object_offset: 0
object_read_count: 100000
object_size: 256
thread_count: 2
