access_key: access
secret_key: secret
host: host.example.org
use_ssl: 0
timeout: 20000
retries: 5
bucket_count: 10
bucket_list_count: 100
bucket_name: HOSTNAME_%04d
bucket_offset: 0
max_ops_per_second: 100
object_count: 100
object_offset: 0
object_read_count: 1000
object_size: 256
thread_count: 2
